name: Build Development Container

on:
  push:
    branches: [ main ]
    paths:
      - '.devcontainer/**'
      - 'scripts/setup-dev-env.sh'
      - 'Dockerfile.dev'
      - '.github/workflows/build-devcontainer.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '.devcontainer/**'
      - 'scripts/setup-dev-env.sh'
      - 'Dockerfile.dev'
      - '.github/workflows/build-devcontainer.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/devcontainer

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.dev
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64

    - name: Update devcontainer.json on main branch
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        # Extract the image digest
        IMAGE_DIGEST=$(docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest --format '{{.Manifest.Digest}}')
        NEW_IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${IMAGE_DIGEST}"
        
        # Update devcontainer.json to use the new image
        sed -i "s|\"image\": \".*\"|\"image\": \"${NEW_IMAGE}\"|" .devcontainer/devcontainer.json
        
        # Commit if there are changes
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .devcontainer/devcontainer.json
        git diff --staged --quiet || git commit -m "chore: update devcontainer image to ${IMAGE_DIGEST:0:12}

🤖 Generated with GitHub Actions

Co-Authored-By: GitHub Actions <action@github.com>"
        git push